# Generated by Django 4.2.9 on 2024-01-08 08:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0024_remove_order_list_order_quantity_order_stuff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuff",
            name="detail",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="내용"
            ),
        ),
        migrations.AlterField(
            model_name="stuff",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
