# Generated by Django 4.2.9 on 2024-01-10 01:06

from django.db import migrations, models
import django.db.models.deletion
import mall.models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0025_alter_stuff_detail_alter_stuff_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True, null=True, upload_to=mall.models.image_upload_path
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="mall.stuff",
                    ),
                ),
            ],
            options={"db_table": "post_image",},
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(blank=True, max_length=200, null=True)),
                ("remain_seat", models.IntegerField(blank=True, null=True)),
                (
                    "f_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.month",
                    ),
                ),
            ],
        ),
    ]
