# Generated by Django 4.2.9 on 2024-01-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0026_month_postimage_day"),
    ]

    operations = [
        migrations.AlterModelTable(name="postimage", table=None,),
    ]
