# Generated by Django 4.2.9 on 2024-01-10 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0028_postimage_add_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="add_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
