# Generated by Django 4.2.9 on 2024-01-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0029_stuff_add_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage", old_name="post", new_name="stuff",
        ),
        migrations.RemoveField(model_name="stuff", name="add_date",),
    ]
